### ISSUE TITLE
Reset password returns 404

### ISSUE THREAD

**Issue by jenschr** [bitraf/p2k16#140] opened 2022-10-10 12:14 UTC
This core feature is broken and needs a fix asap since it directly affects memberships. To reproduce - just test the feature. Upon returning to P2K, you'll get a 404.

**Comment by omega** [comment] 2022-10-10 12:41
as I commented on slack just now, I am unable to reproduce this both locally and in production. I go to https://p2k16.bitraf.no while logged out, I press "forgot password", I get an email and the link takes me to the "Set new password" page. If someone who is able to reproduce this could provide the link that doesn't work (remember to remove the token from the url), and a screenshot of the error message they are getting, that would be most helpful

**Comment by omega** [comment] 2022-10-10 13:23
ok, Thomas Winter pointed me further along, the problem isn't the link in the email, but after you change your password, you get sent to http://p2k16.bitraf.no which gives 404 (although the password is correctly changed).

The reason it gives 404 is that Traefik is not configured to redirect http to https currently (or that p2k16 redirects to a http url not the https one, but Traefik should be fixed either way)

**Comment by jenschr** [comment] 2022-10-10 19:56
Yeah. I'm unable to see this myself since the domain for my Bitraf email no longer exists :-/ But - in both these cases, I asked them to ignore the 404 and just log in with the password they set. Both claimed that the password was not set, idk?

**Closed** 2022-10-26 20:11 UTC
Labels: bug

**Comment by jenschr** [comment] 2022-10-26 20:13
Flott @omega !
